# Generated by Django 2.0.4 on 2018-04-17 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('status', models.CharField(choices=[('ACTIVATED', 'Activated'), ('TERMINATED', 'Terminated'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed')], default='TERMINATED', max_length=15)),
                ('telephone', models.CharField(max_length=25)),
                ('isWorkOnHolidays', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Working_Hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayOfWeek', models.SmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('start', models.TimeField(default='00:00', verbose_name='Start_Time')),
                ('end', models.TimeField(default='23:59', verbose_name='Start_Time')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equeue.Company')),
            ],
        ),
    ]
