# Generated by Django 2.0.4 on 2018-04-17 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equeue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayOfWeek', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(default='00:00', verbose_name='Start_Time')),
                ('end', models.TimeField(default='23:59', verbose_name='End_Time')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equeue.Company')),
                ('dayOfWeeks', models.ManyToManyField(to='equeue.WeekDay')),
            ],
        ),
        migrations.RemoveField(
            model_name='working_hour',
            name='company',
        ),
        migrations.DeleteModel(
            name='Working_Hour',
        ),
    ]
