# Generated by Django 2.0.4 on 2018-04-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equeue', '0002_auto_20180417_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekday',
            name='dayOfWeek',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=1, unique=True),
        ),
    ]
