# Generated by Django 2.0.4 on 2018-04-17 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equeue', '0003_auto_20180417_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workinghour',
            old_name='dayOfWeeks',
            new_name='weekdays',
        ),
    ]
