# Generated by Django 2.0.4 on 2018-04-17 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equeue', '0004_auto_20180417_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExeptionalDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('start', models.TimeField(default='00:00:00', verbose_name='Start_Time')),
                ('end', models.TimeField(default='23:59:59', verbose_name='End_Time')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equeue.Company')),
            ],
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='end',
            field=models.TimeField(default='23:59:59', verbose_name='End_Time'),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='start',
            field=models.TimeField(default='00:00:00', verbose_name='Start_Time'),
        ),
    ]
