# Generated by Django 2.0.4 on 2018-04-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equeue', '0005_auto_20180417_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exeptionalday',
            name='company',
        ),
        migrations.AddField(
            model_name='exeptionalday',
            name='company',
            field=models.ManyToManyField(to='equeue.Company'),
        ),
    ]
