# Generated by Django 2.0.4 on 2018-04-17 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equeue', '0006_auto_20180417_1800'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExeptionalDay',
            new_name='ExeptionDay',
        ),
    ]
